import { useCallback, useEffect, useMemo, useState } from 'react';
import api from '../api/axios';
import { useAdminAuth } from './adminAuthContext';
import { PageTitle } from './AdminBookings';

const configs={
  campaigns:{title:'Campaign',description:'Quản lý các chiến dịch cộng đồng và trạng thái hiển thị.',singular:'campaign',fields:[['title','Tên campaign','text',true],['slug','Slug','text',true],['excerpt','Mô tả ngắn','textarea',true],['content','Nội dung','textarea'],['status','Nhãn trạng thái','text'],['start_date','Ngày bắt đầu','date'],['end_date','Ngày kết thúc','date'],['cover_image','URL ảnh bìa','url'],['display_order','Thứ tự','number'],['is_published','Đang hiển thị','checkbox']]},
  workshops:{title:'Workshop',description:'Quản lý lịch, sức chứa, địa điểm và mức phí workshop.',singular:'workshop',fields:[['title','Tên workshop','text',true],['slug','Slug','text',true],['excerpt','Mô tả ngắn','textarea',true],['description','Nội dung chi tiết','textarea'],['location','Địa điểm','text',true],['starts_at','Bắt đầu','datetime-local',true],['ends_at','Kết thúc','datetime-local',true],['capacity','Sức chứa','number',true],['price','Chi phí (VNĐ)','number'],['cover_image','URL ảnh bìa','url'],['is_published','Đang hiển thị','checkbox']]},
  posts:{title:'Bài viết',description:'Soạn thảo và xuất bản câu chuyện, tin tức của Họa Lụa.',singular:'bài viết',fields:[['title','Tiêu đề','text',true],['slug','Slug','text',true],['category','Chuyên mục','text',true],['excerpt','Mô tả ngắn','textarea',true],['content','Nội dung bài viết','textarea',true],['cover_image','URL ảnh bìa','url'],['published_at','Thời gian xuất bản','datetime-local'],['is_published','Đã xuất bản','checkbox']]},
  gallery:{title:'Thư viện',description:'Quản lý hình ảnh và video trong thư viện nghệ thuật.',singular:'media',fields:[['title','Tên media','text',true],['description','Mô tả','textarea'],['media_type','Loại media','select',true,[['image','Hình ảnh'],['video','Video']]],['media_url','URL media','url',true],['thumbnail_url','URL thumbnail','url'],['display_order','Thứ tự','number'],['is_published','Đang hiển thị','checkbox']]}
};

const apiKey={campaigns:'campaigns',workshops:'workshops',posts:'posts',gallery:'gallery'};
const dateForInput=(value,type)=>value&&type==='datetime-local'?String(value).slice(0,16):value??'';

function AdminResource({resource}){
  const config=configs[resource]; const {user}=useAdminAuth(); const [items,setItems]=useState([]);const [editing,setEditing]=useState(null);const [form,setForm]=useState({});const [state,setState]=useState({loading:true,saving:false,error:'',message:''});
  const empty=useMemo(()=>Object.fromEntries(config.fields.map(([name,,,required,options])=>[name,name==='is_published'?false:(name==='media_type'?(options?.[0]?.[0]||'image'):(required?'':''))])),[config]);
  const load=useCallback(()=>{setState(s=>({...s,loading:true}));api.get(`/admin/${apiKey[resource]}`).then(({data})=>setItems(data.data)).catch(()=>setState(s=>({...s,error:'Không thể tải dữ liệu.'}))).finally(()=>setState(s=>({...s,loading:false})));},[resource]);
  useEffect(()=>{load();},[load]);
  const open=(item=null)=>{setEditing(item);setForm(item?Object.fromEntries(config.fields.map(([name,,type])=>[name,dateForInput(item[name],type)])):empty);setState(s=>({...s,error:'',message:''}));document.querySelector('#resource-editor')?.scrollIntoView({behavior:'smooth'});};
  const submit=async(e)=>{e.preventDefault();setState(s=>({...s,saving:true,error:'',message:''}));try{if(editing)await api.patch(`/admin/${apiKey[resource]}/${editing.id}`,form);else await api.post(`/admin/${apiKey[resource]}`,form);setState(s=>({...s,saving:false,message:'Đã lưu nội dung.'}));await load();if(!editing)setForm(empty);}catch(error){setState(s=>({...s,saving:false,error:error.response?.data?.message||'Không thể lưu nội dung.'}));}};
  const remove=async(item)=>{if(!window.confirm(`Xóa ${config.singular} “${item.title}”? Thao tác này không thể hoàn tác.`))return;await api.delete(`/admin/${apiKey[resource]}/${item.id}`);if(editing?.id===item.id){setEditing(null);setForm(empty);}load();};
  return <><PageTitle title={`Quản lý ${config.title}`} text={config.description} action={<button className="admin-primary" onClick={()=>open()}>+ Thêm {config.singular}</button>}/><div className="admin-resource-layout"><section className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Nội dung</th><th>Trạng thái</th><th>Cập nhật</th><th></th></tr></thead><tbody>{items.map(item=><tr key={item.id}><td><strong>{item.title}</strong><small>{item.slug||item.media_url}</small></td><td><span className={item.is_published?'status status--confirmed':'status status--pending'}>{item.is_published?'Đang hiển thị':'Bản nháp'}</span></td><td>{new Date(item.updated_at).toLocaleDateString('vi-VN')}</td><td className="admin-actions"><button onClick={()=>open(item)}>Sửa</button>{user?.role==='super_admin'&&<button className="is-danger" onClick={()=>remove(item)}>Xóa</button>}</td></tr>)}</tbody></table>{state.loading&&<div className="admin-loading">Đang tải…</div>}{!state.loading&&!items.length&&<div className="admin-empty">Chưa có nội dung. Hãy tạo mục đầu tiên.</div>}</section><form id="resource-editor" className="admin-editor" onSubmit={submit}><div className="admin-editor__head"><div><p className="admin-kicker">{editing?'Chỉnh sửa':'Tạo mới'}</p><h2>{editing?.title||config.title}</h2></div>{editing&&<button type="button" onClick={()=>open()}>Đóng</button>}</div><div className="admin-form-grid">{config.fields.map(([name,label,type,required,options])=><label key={name} className={type==='textarea'?'is-wide':''}>{type==='checkbox'?<><input type="checkbox" checked={Boolean(form[name])} onChange={e=>setForm({...form,[name]:e.target.checked})}/><span>{label}</span></>:<><span>{label}{required?' *':''}</span>{type==='textarea'?<textarea rows={name==='content'?8:3} required={required} value={form[name]??''} onChange={e=>setForm({...form,[name]:e.target.value})}/>:type==='select'?<select required={required} value={form[name]??''} onChange={e=>setForm({...form,[name]:e.target.value})}>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>:<input type={type} required={required} min={type==='number'?0:undefined} value={form[name]??''} onChange={e=>setForm({...form,[name]:e.target.value})}/>}</>}</label>)}</div>{state.error&&<div className="admin-alert is-error">{state.error}</div>}{state.message&&<div className="admin-alert is-success">{state.message}</div>}<button className="admin-primary" disabled={state.saving}>{state.saving?'Đang lưu…':'Lưu nội dung'}</button></form></div></>;
}
export default AdminResource;
